/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AfiliadosRouteImport } from './routes/afiliados'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PublicidadeRouteImport } from './routes/publicidade'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AdminCarrosselRouteImport } from './routes/admin.carrossel'
import { Route as AdminCategoriasRouteImport } from './routes/admin.categorias'
import { Route as AdminClientesRouteImport } from './routes/admin.clientes'
import { Route as AdminComentariosRouteImport } from './routes/admin.comentarios'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminPedidosRouteImport } from './routes/admin.pedidos'
import { Route as AdminPostsRouteImport } from './routes/admin.posts'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as CatalogoIndexRouteImport } from './routes/catalogo.index'
import { Route as CatalogoSlugRouteImport } from './routes/catalogo.$slug'
import { Route as CheckoutConfirmadoRouteImport } from './routes/checkout.confirmado'
import { Route as ContaIndexRouteImport } from './routes/conta.index'
import { Route as ContaLoginRouteImport } from './routes/conta.login'
import { Route as AdminBlogIndexRouteImport } from './routes/admin.blog.index'
import { Route as AdminBlogIdRouteImport } from './routes/admin.blog.$id'
import { Route as AdminBlogNovoRouteImport } from './routes/admin.blog.novo'
import { Route as AdminPostsIndexRouteImport } from './routes/admin.posts.index'
import { Route as AdminPostsIdRouteImport } from './routes/admin.posts.$id'
import { Route as AdminPostsNovoRouteImport } from './routes/admin.posts.novo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AfiliadosRoute = AfiliadosRouteImport.update({
  id: '/afiliados',
  path: '/afiliados',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicidadeRoute = PublicidadeRouteImport.update({
  id: '/publicidade',
  path: '/publicidade',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCarrosselRoute = AdminCarrosselRouteImport.update({
  id: '/carrossel',
  path: '/carrossel',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriasRoute = AdminCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComentariosRoute = AdminComentariosRouteImport.update({
  id: '/comentarios',
  path: '/comentarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsRoute = AdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const CatalogoIndexRoute = CatalogoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CatalogoRoute,
} as any)
const CatalogoSlugRoute = CatalogoSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CatalogoRoute,
} as any)
const CheckoutConfirmadoRoute = CheckoutConfirmadoRouteImport.update({
  id: '/confirmado',
  path: '/confirmado',
  getParentRoute: () => CheckoutRoute,
} as any)
const ContaIndexRoute = ContaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContaRoute,
} as any)
const ContaLoginRoute = ContaLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => ContaRoute,
} as any)
const AdminBlogIndexRoute = AdminBlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminBlogRoute,
} as any)
const AdminBlogIdRoute = AdminBlogIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminBlogRoute,
} as any)
const AdminBlogNovoRoute = AdminBlogNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AdminBlogRoute,
} as any)
const AdminPostsIndexRoute = AdminPostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminPostsRoute,
} as any)
const AdminPostsIdRoute = AdminPostsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminPostsRoute,
} as any)
const AdminPostsNovoRoute = AdminPostsNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AdminPostsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/afiliados': typeof AfiliadosRoute
  '/blog': typeof BlogRouteWithChildren
  '/carrinho': typeof CarrinhoRoute
  '/catalogo': typeof CatalogoRouteWithChildren
  '/checkout': typeof CheckoutRouteWithChildren
  '/conta': typeof ContaRouteWithChildren
  '/contato': typeof ContatoRoute
  '/cookies': typeof CookiesRoute
  '/favoritos': typeof FavoritosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/publicidade': typeof PublicidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/admin/blog': typeof AdminBlogRouteWithChildren
  '/admin/carrossel': typeof AdminCarrosselRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/comentarios': typeof AdminComentariosRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/posts': typeof AdminPostsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/catalogo/$slug': typeof CatalogoSlugRoute
  '/checkout/confirmado': typeof CheckoutConfirmadoRoute
  '/conta/login': typeof ContaLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/catalogo/': typeof CatalogoIndexRoute
  '/conta/': typeof ContaIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/blog/novo': typeof AdminBlogNovoRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
  '/admin/posts/novo': typeof AdminPostsNovoRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/afiliados': typeof AfiliadosRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contato': typeof ContatoRoute
  '/cookies': typeof CookiesRoute
  '/favoritos': typeof FavoritosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/publicidade': typeof PublicidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/admin/carrossel': typeof AdminCarrosselRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/comentarios': typeof AdminComentariosRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/catalogo/$slug': typeof CatalogoSlugRoute
  '/checkout/confirmado': typeof CheckoutConfirmadoRoute
  '/conta/login': typeof ContaLoginRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/catalogo': typeof CatalogoIndexRoute
  '/conta': typeof ContaIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/blog/novo': typeof AdminBlogNovoRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
  '/admin/posts/novo': typeof AdminPostsNovoRoute
  '/admin/blog': typeof AdminBlogIndexRoute
  '/admin/posts': typeof AdminPostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/afiliados': typeof AfiliadosRoute
  '/blog': typeof BlogRouteWithChildren
  '/carrinho': typeof CarrinhoRoute
  '/catalogo': typeof CatalogoRouteWithChildren
  '/checkout': typeof CheckoutRouteWithChildren
  '/conta': typeof ContaRouteWithChildren
  '/contato': typeof ContatoRoute
  '/cookies': typeof CookiesRoute
  '/favoritos': typeof FavoritosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/publicidade': typeof PublicidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/admin/blog': typeof AdminBlogRouteWithChildren
  '/admin/carrossel': typeof AdminCarrosselRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/comentarios': typeof AdminComentariosRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/posts': typeof AdminPostsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/catalogo/$slug': typeof CatalogoSlugRoute
  '/checkout/confirmado': typeof CheckoutConfirmadoRoute
  '/conta/login': typeof ContaLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/catalogo/': typeof CatalogoIndexRoute
  '/conta/': typeof ContaIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/blog/novo': typeof AdminBlogNovoRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
  '/admin/posts/novo': typeof AdminPostsNovoRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/afiliados'
    | '/blog'
    | '/carrinho'
    | '/catalogo'
    | '/checkout'
    | '/conta'
    | '/contato'
    | '/cookies'
    | '/favoritos'
    | '/privacidade'
    | '/publicidade'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos'
    | '/admin/blog'
    | '/admin/carrossel'
    | '/admin/categorias'
    | '/admin/clientes'
    | '/admin/comentarios'
    | '/admin/login'
    | '/admin/pedidos'
    | '/admin/posts'
    | '/admin/settings'
    | '/blog/$slug'
    | '/catalogo/$slug'
    | '/checkout/confirmado'
    | '/conta/login'
    | '/admin/'
    | '/blog/'
    | '/catalogo/'
    | '/conta/'
    | '/admin/blog/$id'
    | '/admin/blog/novo'
    | '/admin/posts/$id'
    | '/admin/posts/novo'
    | '/admin/blog/'
    | '/admin/posts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/afiliados'
    | '/carrinho'
    | '/checkout'
    | '/contato'
    | '/cookies'
    | '/favoritos'
    | '/privacidade'
    | '/publicidade'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos'
    | '/admin/carrossel'
    | '/admin/categorias'
    | '/admin/clientes'
    | '/admin/comentarios'
    | '/admin/login'
    | '/admin/pedidos'
    | '/admin/settings'
    | '/blog/$slug'
    | '/catalogo/$slug'
    | '/checkout/confirmado'
    | '/conta/login'
    | '/admin'
    | '/blog'
    | '/catalogo'
    | '/conta'
    | '/admin/blog/$id'
    | '/admin/blog/novo'
    | '/admin/posts/$id'
    | '/admin/posts/novo'
    | '/admin/blog'
    | '/admin/posts'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/afiliados'
    | '/blog'
    | '/carrinho'
    | '/catalogo'
    | '/checkout'
    | '/conta'
    | '/contato'
    | '/cookies'
    | '/favoritos'
    | '/privacidade'
    | '/publicidade'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos'
    | '/admin/blog'
    | '/admin/carrossel'
    | '/admin/categorias'
    | '/admin/clientes'
    | '/admin/comentarios'
    | '/admin/login'
    | '/admin/pedidos'
    | '/admin/posts'
    | '/admin/settings'
    | '/blog/$slug'
    | '/catalogo/$slug'
    | '/checkout/confirmado'
    | '/conta/login'
    | '/admin/'
    | '/blog/'
    | '/catalogo/'
    | '/conta/'
    | '/admin/blog/$id'
    | '/admin/blog/novo'
    | '/admin/posts/$id'
    | '/admin/posts/novo'
    | '/admin/blog/'
    | '/admin/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AfiliadosRoute: typeof AfiliadosRoute
  BlogRoute: typeof BlogRouteWithChildren
  CarrinhoRoute: typeof CarrinhoRoute
  CatalogoRoute: typeof CatalogoRouteWithChildren
  CheckoutRoute: typeof CheckoutRouteWithChildren
  ContaRoute: typeof ContaRouteWithChildren
  ContatoRoute: typeof ContatoRoute
  CookiesRoute: typeof CookiesRoute
  FavoritosRoute: typeof FavoritosRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  PublicidadeRoute: typeof PublicidadeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  TermosRoute: typeof TermosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/afiliados': {
      id: '/afiliados'
      path: '/afiliados'
      fullPath: '/afiliados'
      preLoaderRoute: typeof AfiliadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicidade': {
      id: '/publicidade'
      path: '/publicidade'
      fullPath: '/publicidade'
      preLoaderRoute: typeof PublicidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/carrossel': {
      id: '/admin/carrossel'
      path: '/carrossel'
      fullPath: '/admin/carrossel'
      preLoaderRoute: typeof AdminCarrosselRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categorias': {
      id: '/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AdminCategoriasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comentarios': {
      id: '/admin/comentarios'
      path: '/comentarios'
      fullPath: '/admin/comentarios'
      preLoaderRoute: typeof AdminComentariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts': {
      id: '/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/catalogo/': {
      id: '/catalogo/'
      path: '/'
      fullPath: '/catalogo/'
      preLoaderRoute: typeof CatalogoIndexRouteImport
      parentRoute: typeof CatalogoRoute
    }
    '/catalogo/$slug': {
      id: '/catalogo/$slug'
      path: '/$slug'
      fullPath: '/catalogo/$slug'
      preLoaderRoute: typeof CatalogoSlugRouteImport
      parentRoute: typeof CatalogoRoute
    }
    '/checkout/confirmado': {
      id: '/checkout/confirmado'
      path: '/confirmado'
      fullPath: '/checkout/confirmado'
      preLoaderRoute: typeof CheckoutConfirmadoRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/conta/': {
      id: '/conta/'
      path: '/'
      fullPath: '/conta/'
      preLoaderRoute: typeof ContaIndexRouteImport
      parentRoute: typeof ContaRoute
    }
    '/conta/login': {
      id: '/conta/login'
      path: '/login'
      fullPath: '/conta/login'
      preLoaderRoute: typeof ContaLoginRouteImport
      parentRoute: typeof ContaRoute
    }
    '/admin/blog/': {
      id: '/admin/blog/'
      path: '/'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AdminBlogIndexRouteImport
      parentRoute: typeof AdminBlogRoute
    }
    '/admin/blog/$id': {
      id: '/admin/blog/$id'
      path: '/$id'
      fullPath: '/admin/blog/$id'
      preLoaderRoute: typeof AdminBlogIdRouteImport
      parentRoute: typeof AdminBlogRoute
    }
    '/admin/blog/novo': {
      id: '/admin/blog/novo'
      path: '/novo'
      fullPath: '/admin/blog/novo'
      preLoaderRoute: typeof AdminBlogNovoRouteImport
      parentRoute: typeof AdminBlogRoute
    }
    '/admin/posts/': {
      id: '/admin/posts/'
      path: '/'
      fullPath: '/admin/posts/'
      preLoaderRoute: typeof AdminPostsIndexRouteImport
      parentRoute: typeof AdminPostsRoute
    }
    '/admin/posts/$id': {
      id: '/admin/posts/$id'
      path: '/$id'
      fullPath: '/admin/posts/$id'
      preLoaderRoute: typeof AdminPostsIdRouteImport
      parentRoute: typeof AdminPostsRoute
    }
    '/admin/posts/novo': {
      id: '/admin/posts/novo'
      path: '/novo'
      fullPath: '/admin/posts/novo'
      preLoaderRoute: typeof AdminPostsNovoRouteImport
      parentRoute: typeof AdminPostsRoute
    }
  }
}

interface AdminBlogRouteChildren {
  AdminBlogIdRoute: typeof AdminBlogIdRoute
  AdminBlogNovoRoute: typeof AdminBlogNovoRoute
  AdminBlogIndexRoute: typeof AdminBlogIndexRoute
}

const AdminBlogRouteChildren: AdminBlogRouteChildren = {
  AdminBlogIdRoute: AdminBlogIdRoute,
  AdminBlogNovoRoute: AdminBlogNovoRoute,
  AdminBlogIndexRoute: AdminBlogIndexRoute,
}

const AdminBlogRouteWithChildren = AdminBlogRoute._addFileChildren(
  AdminBlogRouteChildren,
)

interface AdminPostsRouteChildren {
  AdminPostsIdRoute: typeof AdminPostsIdRoute
  AdminPostsNovoRoute: typeof AdminPostsNovoRoute
  AdminPostsIndexRoute: typeof AdminPostsIndexRoute
}

const AdminPostsRouteChildren: AdminPostsRouteChildren = {
  AdminPostsIdRoute: AdminPostsIdRoute,
  AdminPostsNovoRoute: AdminPostsNovoRoute,
  AdminPostsIndexRoute: AdminPostsIndexRoute,
}

const AdminPostsRouteWithChildren = AdminPostsRoute._addFileChildren(
  AdminPostsRouteChildren,
)

interface AdminRouteChildren {
  AdminBlogRoute: typeof AdminBlogRouteWithChildren
  AdminCarrosselRoute: typeof AdminCarrosselRoute
  AdminCategoriasRoute: typeof AdminCategoriasRoute
  AdminClientesRoute: typeof AdminClientesRoute
  AdminComentariosRoute: typeof AdminComentariosRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPedidosRoute: typeof AdminPedidosRoute
  AdminPostsRoute: typeof AdminPostsRouteWithChildren
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBlogRoute: AdminBlogRouteWithChildren,
  AdminCarrosselRoute: AdminCarrosselRoute,
  AdminCategoriasRoute: AdminCategoriasRoute,
  AdminClientesRoute: AdminClientesRoute,
  AdminComentariosRoute: AdminComentariosRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPedidosRoute: AdminPedidosRoute,
  AdminPostsRoute: AdminPostsRouteWithChildren,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface CatalogoRouteChildren {
  CatalogoSlugRoute: typeof CatalogoSlugRoute
  CatalogoIndexRoute: typeof CatalogoIndexRoute
}

const CatalogoRouteChildren: CatalogoRouteChildren = {
  CatalogoSlugRoute: CatalogoSlugRoute,
  CatalogoIndexRoute: CatalogoIndexRoute,
}

const CatalogoRouteWithChildren = CatalogoRoute._addFileChildren(
  CatalogoRouteChildren,
)

interface CheckoutRouteChildren {
  CheckoutConfirmadoRoute: typeof CheckoutConfirmadoRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutConfirmadoRoute: CheckoutConfirmadoRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

interface ContaRouteChildren {
  ContaLoginRoute: typeof ContaLoginRoute
  ContaIndexRoute: typeof ContaIndexRoute
}

const ContaRouteChildren: ContaRouteChildren = {
  ContaLoginRoute: ContaLoginRoute,
  ContaIndexRoute: ContaIndexRoute,
}

const ContaRouteWithChildren = ContaRoute._addFileChildren(ContaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AfiliadosRoute: AfiliadosRoute,
  BlogRoute: BlogRouteWithChildren,
  CarrinhoRoute: CarrinhoRoute,
  CatalogoRoute: CatalogoRouteWithChildren,
  CheckoutRoute: CheckoutRouteWithChildren,
  ContaRoute: ContaRouteWithChildren,
  ContatoRoute: ContatoRoute,
  CookiesRoute: CookiesRoute,
  FavoritosRoute: FavoritosRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  PublicidadeRoute: PublicidadeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  TermosRoute: TermosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
